Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
training, test = train_test_split(scaled, train_size = 0.8, test_size = 0.2, shuffle=False)
training_label, test_label = train_test_split(yBaru, train_size = 0.8, test_size = 0.2, shuffle=False)

clf2 = GaussianNB()
clf2.fit(training, training_label)

probas = clf2.predict_proba(test)
probas = probas[:,1]
probas.shape

probas

test_label
------------------

[0;31m[0m
[0;31mNameError[0mTraceback (most recent call last)
[0;32m<ipython-input-51-268cfe785842>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mtraining[0m[0;34m,[0m [0mtest[0m [0;34m=[0m [0mtrain_test_split[0m[0;34m([0m[0mscaled[0m[0;34m,[0m [0mtrain_size[0m [0;34m=[0m [0;36m0.8[0m[0;34m,[0m [0mtest_size[0m [0;34m=[0m [0;36m0.2[0m[0;34m,[0m [0mshuffle[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mtraining_label[0m[0;34m,[0m [0mtest_label[0m [0;34m=[0m [0mtrain_test_split[0m[0;34m([0m[0myBaru[0m[0;34m,[0m [0mtrain_size[0m [0;34m=[0m [0;36m0.8[0m[0;34m,[0m [0mtest_size[0m [0;34m=[0m [0;36m0.2[0m[0;34m,[0m [0mshuffle[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0mclf2[0m [0;34m=[0m [0mGaussianNB[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mclf2[0m[0;34m.[0m[0mfit[0m[0;34m([0m[0mtraining[0m[0;34m,[0m [0mtraining_label[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'yBaru' is not defined
NameError: name 'yBaru' is not defined

